# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\GitHub\Wine-Inventory\interface.ui',
# licensing of 'D:\Documents\GitHub\Wine-Inventory\interface.ui' applies.
#
<<<<<<< HEAD
# Created: Tue Jan 29 17:07:38 2019
=======
# Created: Tue Jan 29 15:16:13 2019
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Vinny(object):
    def setupUi(self, Vinny):
        Vinny.setObjectName("Vinny")
        Vinny.resize(1117, 816)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Wine/wine/icons8-bar-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Vinny.setWindowIcon(icon)
        Vinny.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(Vinny)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.main_tab.setObjectName("main_tab")
        self.inventory = QtWidgets.QWidget()
        self.inventory.setObjectName("inventory")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inventory)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bottle_lookup = QtWidgets.QGroupBox(self.inventory)
        self.bottle_lookup.setObjectName("bottle_lookup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bottle_lookup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.bottle_lookup)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
<<<<<<< HEAD
        self.InventoryWineID = QtWidgets.QLineEdit(self.bottle_lookup)
        self.InventoryWineID.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.InventoryWineID.setText("")
        self.InventoryWineID.setClearButtonEnabled(False)
        self.InventoryWineID.setObjectName("InventoryWineID")
        self.verticalLayout.addWidget(self.InventoryWineID)
        self.label = QtWidgets.QLabel(self.bottle_lookup)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.InventoryLocation = QtWidgets.QLineEdit(self.bottle_lookup)
        self.InventoryLocation.setObjectName("InventoryLocation")
        self.verticalLayout.addWidget(self.InventoryLocation)
        self.InventorySearch = QtWidgets.QPushButton(self.bottle_lookup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Actions/actions/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InventorySearch.setIcon(icon1)
        self.InventorySearch.setCheckable(False)
        self.InventorySearch.setObjectName("InventorySearch")
        self.verticalLayout.addWidget(self.InventorySearch)
=======
        self.wine_id = QtWidgets.QLineEdit(self.bottle_lookup)
        self.wine_id.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.wine_id.setText("")
        self.wine_id.setClearButtonEnabled(False)
        self.wine_id.setObjectName("wine_id")
        self.verticalLayout.addWidget(self.wine_id)
        self.label = QtWidgets.QLabel(self.bottle_lookup)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.location_field = QtWidgets.QLineEdit(self.bottle_lookup)
        self.location_field.setObjectName("location_field")
        self.verticalLayout.addWidget(self.location_field)
        self.quick_search = QtWidgets.QPushButton(self.bottle_lookup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Actions/actions/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quick_search.setIcon(icon1)
        self.quick_search.setCheckable(False)
        self.quick_search.setObjectName("quick_search")
        self.verticalLayout.addWidget(self.quick_search)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.horizontalLayout.addWidget(self.bottle_lookup)
        self.groupBox = QtWidgets.QGroupBox(self.inventory)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
<<<<<<< HEAD
        self.InventorySortBy = QtWidgets.QComboBox(self.groupBox)
        self.InventorySortBy.setObjectName("InventorySortBy")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.verticalLayout_3.addWidget(self.InventorySortBy)
        self.InventorySortAsc = QtWidgets.QRadioButton(self.groupBox)
        self.InventorySortAsc.setChecked(True)
        self.InventorySortAsc.setObjectName("InventorySortAsc")
        self.verticalLayout_3.addWidget(self.InventorySortAsc)
        self.InventorySortDesc = QtWidgets.QRadioButton(self.groupBox)
        self.InventorySortDesc.setObjectName("InventorySortDesc")
        self.verticalLayout_3.addWidget(self.InventorySortDesc)
        self.InventoryRefresh = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Actions/actions/stock_refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InventoryRefresh.setIcon(icon2)
        self.InventoryRefresh.setObjectName("InventoryRefresh")
        self.verticalLayout_3.addWidget(self.InventoryRefresh)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.InventoryTable = QtWidgets.QTableWidget(self.inventory)
        self.InventoryTable.setObjectName("InventoryTable")
        self.InventoryTable.setColumnCount(0)
        self.InventoryTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.InventoryTable)
        self.InventoryCheckOut = QtWidgets.QPushButton(self.inventory)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Wine/wine/icons8-wine-bottle-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InventoryCheckOut.setIcon(icon3)
        self.InventoryCheckOut.setObjectName("InventoryCheckOut")
        self.verticalLayout_2.addWidget(self.InventoryCheckOut)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.InventoryAddCopy = QtWidgets.QPushButton(self.inventory)
        self.InventoryAddCopy.setObjectName("InventoryAddCopy")
        self.horizontalLayout_6.addWidget(self.InventoryAddCopy)
        self.InventoryEditBottle = QtWidgets.QPushButton(self.inventory)
        self.InventoryEditBottle.setObjectName("InventoryEditBottle")
        self.horizontalLayout_6.addWidget(self.InventoryEditBottle)
        self.InventoryMoveBottle = QtWidgets.QPushButton(self.inventory)
        self.InventoryMoveBottle.setObjectName("InventoryMoveBottle")
        self.horizontalLayout_6.addWidget(self.InventoryMoveBottle)
=======
        self.sort_by = QtWidgets.QComboBox(self.groupBox)
        self.sort_by.setObjectName("sort_by")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.verticalLayout_3.addWidget(self.sort_by)
        self.sort_asc = QtWidgets.QRadioButton(self.groupBox)
        self.sort_asc.setChecked(True)
        self.sort_asc.setObjectName("sort_asc")
        self.verticalLayout_3.addWidget(self.sort_asc)
        self.sort_desc = QtWidgets.QRadioButton(self.groupBox)
        self.sort_desc.setObjectName("sort_desc")
        self.verticalLayout_3.addWidget(self.sort_desc)
        self.refresh = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Actions/actions/stock_refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon2)
        self.refresh.setObjectName("refresh")
        self.verticalLayout_3.addWidget(self.refresh)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.invTable = QtWidgets.QTableView(self.inventory)
        self.invTable.setObjectName("invTable")
        self.verticalLayout_2.addWidget(self.invTable)
        self.check_out = QtWidgets.QPushButton(self.inventory)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Wine/wine/icons8-wine-bottle-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_out.setIcon(icon3)
        self.check_out.setObjectName("check_out")
        self.verticalLayout_2.addWidget(self.check_out)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_copy = QtWidgets.QPushButton(self.inventory)
        self.add_copy.setObjectName("add_copy")
        self.horizontalLayout_6.addWidget(self.add_copy)
        self.edit_bottle = QtWidgets.QPushButton(self.inventory)
        self.edit_bottle.setObjectName("edit_bottle")
        self.horizontalLayout_6.addWidget(self.edit_bottle)
        self.move_bottle = QtWidgets.QPushButton(self.inventory)
        self.move_bottle.setObjectName("move_bottle")
        self.horizontalLayout_6.addWidget(self.move_bottle)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.main_tab.addTab(self.inventory, "")
        self.find = QtWidgets.QWidget()
        self.find.setObjectName("find")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.find)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.find)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
<<<<<<< HEAD
        self.AddBottleTable = QtWidgets.QTableWidget(self.find)
        self.AddBottleTable.setObjectName("AddBottleTable")
        self.AddBottleTable.setColumnCount(0)
        self.AddBottleTable.setRowCount(0)
        self.verticalLayout_6.addWidget(self.AddBottleTable)
=======
        self.search_result_table = QtWidgets.QTableView(self.find)
        self.search_result_table.setObjectName("search_result_table")
        self.verticalLayout_6.addWidget(self.search_result_table)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 1, 2, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.find)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
<<<<<<< HEAD
        self.AddBottleSelLocation = QtWidgets.QRadioButton(self.groupBox_5)
        self.AddBottleSelLocation.setChecked(True)
        self.AddBottleSelLocation.setObjectName("AddBottleSelLocation")
        self.verticalLayout_9.addWidget(self.AddBottleSelLocation)
        self.AddBottleLocation = QtWidgets.QLineEdit(self.groupBox_5)
        self.AddBottleLocation.setObjectName("AddBottleLocation")
        self.verticalLayout_9.addWidget(self.AddBottleLocation)
        self.AddBottleSelQty = QtWidgets.QRadioButton(self.groupBox_5)
        self.AddBottleSelQty.setObjectName("AddBottleSelQty")
        self.verticalLayout_9.addWidget(self.AddBottleSelQty)
        self.AddBottleQty = QtWidgets.QLineEdit(self.groupBox_5)
        self.AddBottleQty.setObjectName("AddBottleQty")
        self.verticalLayout_9.addWidget(self.AddBottleQty)
        self.AddBottleAdd = QtWidgets.QPushButton(self.groupBox_5)
        self.AddBottleAdd.setObjectName("AddBottleAdd")
        self.verticalLayout_9.addWidget(self.AddBottleAdd)
        self.AddBottleGenerateBarcode = QtWidgets.QPushButton(self.groupBox_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Actions/actions/icons8-barcode-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddBottleGenerateBarcode.setIcon(icon4)
        self.AddBottleGenerateBarcode.setObjectName("AddBottleGenerateBarcode")
        self.verticalLayout_9.addWidget(self.AddBottleGenerateBarcode)
=======
        self.sel_location = QtWidgets.QRadioButton(self.groupBox_5)
        self.sel_location.setChecked(True)
        self.sel_location.setObjectName("sel_location")
        self.verticalLayout_9.addWidget(self.sel_location)
        self.location = QtWidgets.QLineEdit(self.groupBox_5)
        self.location.setObjectName("location")
        self.verticalLayout_9.addWidget(self.location)
        self.sel_quantity = QtWidgets.QRadioButton(self.groupBox_5)
        self.sel_quantity.setObjectName("sel_quantity")
        self.verticalLayout_9.addWidget(self.sel_quantity)
        self.qty = QtWidgets.QLineEdit(self.groupBox_5)
        self.qty.setObjectName("qty")
        self.verticalLayout_9.addWidget(self.qty)
        self.add = QtWidgets.QPushButton(self.groupBox_5)
        self.add.setObjectName("add")
        self.verticalLayout_9.addWidget(self.add)
        self.generate_barcode = QtWidgets.QPushButton(self.groupBox_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Actions/actions/icons8-barcode-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_barcode.setIcon(icon4)
        self.generate_barcode.setObjectName("generate_barcode")
        self.verticalLayout_9.addWidget(self.generate_barcode)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.find)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
<<<<<<< HEAD
        self.AddBottleAVA = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleAVA.setPlaceholderText("")
        self.AddBottleAVA.setObjectName("AddBottleAVA")
        self.verticalLayout_5.addWidget(self.AddBottleAVA)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.AddBottleVarietal = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleVarietal.setPlaceholderText("")
        self.AddBottleVarietal.setObjectName("AddBottleVarietal")
        self.verticalLayout_5.addWidget(self.AddBottleVarietal)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.AddBottleUPC = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleUPC.setObjectName("AddBottleUPC")
        self.verticalLayout_5.addWidget(self.AddBottleUPC)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.AddBottleType = QtWidgets.QComboBox(self.groupBox_3)
        self.AddBottleType.setObjectName("AddBottleType")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.verticalLayout_5.addWidget(self.AddBottleType)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.AddBottleCurrentValue = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleCurrentValue.setObjectName("AddBottleCurrentValue")
        self.verticalLayout_5.addWidget(self.AddBottleCurrentValue)
=======
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.varietal = QtWidgets.QLineEdit(self.groupBox_3)
        self.varietal.setPlaceholderText("")
        self.varietal.setObjectName("varietal")
        self.verticalLayout_5.addWidget(self.varietal)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.upc = QtWidgets.QLineEdit(self.groupBox_3)
        self.upc.setObjectName("upc")
        self.verticalLayout_5.addWidget(self.upc)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.value = QtWidgets.QLineEdit(self.groupBox_3)
        self.value.setObjectName("value")
        self.verticalLayout_5.addWidget(self.value)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
<<<<<<< HEAD
        self.AddBottleWinery = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleWinery.setPlaceholderText("")
        self.AddBottleWinery.setObjectName("AddBottleWinery")
        self.verticalLayout_4.addWidget(self.AddBottleWinery)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.AddBottleBlendName = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleBlendName.setObjectName("AddBottleBlendName")
        self.verticalLayout_4.addWidget(self.AddBottleBlendName)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.AddBottleVintage = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleVintage.setObjectName("AddBottleVintage")
        self.verticalLayout_4.addWidget(self.AddBottleVintage)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.AddBottleBottleSize = QtWidgets.QComboBox(self.groupBox_3)
        self.AddBottleBottleSize.setObjectName("AddBottleBottleSize")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.verticalLayout_4.addWidget(self.AddBottleBottleSize)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.AddBottleMSRP = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleMSRP.setObjectName("AddBottleMSRP")
        self.verticalLayout_4.addWidget(self.AddBottleMSRP)
=======
        self.winery = QtWidgets.QLineEdit(self.groupBox_3)
        self.winery.setPlaceholderText("")
        self.winery.setObjectName("winery")
        self.verticalLayout_4.addWidget(self.winery)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.blend_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.blend_name.setObjectName("blend_name")
        self.verticalLayout_4.addWidget(self.blend_name)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.vintage = QtWidgets.QLineEdit(self.groupBox_3)
        self.vintage.setObjectName("vintage")
        self.verticalLayout_4.addWidget(self.vintage)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.bottle_size = QtWidgets.QComboBox(self.groupBox_3)
        self.bottle_size.setObjectName("bottle_size")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.bottle_size.addItem("")
        self.verticalLayout_4.addWidget(self.bottle_size)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.msrp = QtWidgets.QLineEdit(self.groupBox_3)
        self.msrp.setObjectName("msrp")
        self.verticalLayout_4.addWidget(self.msrp)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
<<<<<<< HEAD
        self.AddBottleComments = QtWidgets.QTextEdit(self.groupBox_3)
        self.AddBottleComments.setPlaceholderText("")
        self.AddBottleComments.setObjectName("AddBottleComments")
        self.gridLayout_2.addWidget(self.AddBottleComments, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.AddBottleCellarOnly = QtWidgets.QCheckBox(self.groupBox_3)
        self.AddBottleCellarOnly.setChecked(True)
        self.AddBottleCellarOnly.setObjectName("AddBottleCellarOnly")
        self.verticalLayout_7.addWidget(self.AddBottleCellarOnly)
        self.AddBottleSearch = QtWidgets.QPushButton(self.groupBox_3)
        self.AddBottleSearch.setIcon(icon1)
        self.AddBottleSearch.setObjectName("AddBottleSearch")
        self.verticalLayout_7.addWidget(self.AddBottleSearch)
        self.AddBottleCheckOut = QtWidgets.QPushButton(self.groupBox_3)
        self.AddBottleCheckOut.setIcon(icon3)
        self.AddBottleCheckOut.setObjectName("AddBottleCheckOut")
        self.verticalLayout_7.addWidget(self.AddBottleCheckOut)
        self.AddBottleUpdate = QtWidgets.QPushButton(self.groupBox_3)
        self.AddBottleUpdate.setObjectName("AddBottleUpdate")
        self.verticalLayout_7.addWidget(self.AddBottleUpdate)
        self.AddBottleMove = QtWidgets.QPushButton(self.groupBox_3)
        self.AddBottleMove.setObjectName("AddBottleMove")
        self.verticalLayout_7.addWidget(self.AddBottleMove)
=======
        self.comments = QtWidgets.QTextEdit(self.groupBox_3)
        self.comments.setPlaceholderText("")
        self.comments.setObjectName("comments")
        self.gridLayout_2.addWidget(self.comments, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cellar_only = QtWidgets.QCheckBox(self.groupBox_3)
        self.cellar_only.setChecked(True)
        self.cellar_only.setObjectName("cellar_only")
        self.verticalLayout_7.addWidget(self.cellar_only)
        self.search = QtWidgets.QPushButton(self.groupBox_3)
        self.search.setObjectName("search")
        self.verticalLayout_7.addWidget(self.search)
        self.update = QtWidgets.QPushButton(self.groupBox_3)
        self.update.setObjectName("update")
        self.verticalLayout_7.addWidget(self.update)
        self.move_bottle_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.move_bottle_2.setObjectName("move_bottle_2")
        self.verticalLayout_7.addWidget(self.move_bottle_2)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.gridLayout_2.addLayout(self.verticalLayout_7, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.main_tab.addTab(self.find, "")
        self.history = QtWidgets.QWidget()
        self.history.setObjectName("history")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.history)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
<<<<<<< HEAD
        self.HistoryTable = QtWidgets.QTableWidget(self.history)
        self.HistoryTable.setObjectName("HistoryTable")
        self.HistoryTable.setColumnCount(0)
        self.HistoryTable.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.HistoryTable)
=======
        self.history_table = QtWidgets.QTableView(self.history)
        self.history_table.setObjectName("history_table")
        self.horizontalLayout_3.addWidget(self.history_table)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.main_tab.addTab(self.history, "")
        self.horizontalLayout_2.addWidget(self.main_tab)
        Vinny.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Vinny)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Vinny.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Vinny)
        self.statusbar.setObjectName("statusbar")
        Vinny.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(Vinny)
        self.actionSettings.setShortcutContext(QtCore.Qt.WidgetWithChildrenShortcut)
        self.actionSettings.setObjectName("actionSettings")
        self.actionImport = QtWidgets.QAction(Vinny)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Actions/actions/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon5)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(Vinny)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Mimetypes/mimetypes/x-office-spreadsheet.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon6)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Vinny)
        self.main_tab.setCurrentIndex(0)
<<<<<<< HEAD
        self.InventorySortBy.setCurrentIndex(0)
        self.AddBottleBottleSize.setCurrentIndex(2)
        QtCore.QObject.connect(self.InventoryWineID, QtCore.SIGNAL("returnPressed()"), self.InventorySearch.animateClick)
        QtCore.QObject.connect(self.InventoryLocation, QtCore.SIGNAL("returnPressed()"), self.InventorySearch.animateClick)
        QtCore.QObject.connect(self.InventoryRefresh, QtCore.SIGNAL("clicked()"), self.InventorySearch.click)
        QtCore.QObject.connect(self.AddBottleCellarOnly, QtCore.SIGNAL("toggled(bool)"), self.AddBottleSearch.animateClick)
        QtCore.QMetaObject.connectSlotsByName(Vinny)
        Vinny.setTabOrder(self.InventoryWineID, self.InventoryLocation)
        Vinny.setTabOrder(self.InventoryLocation, self.InventorySearch)
        Vinny.setTabOrder(self.InventorySearch, self.InventoryTable)
        Vinny.setTabOrder(self.InventoryTable, self.InventoryCheckOut)
        Vinny.setTabOrder(self.InventoryCheckOut, self.InventoryAddCopy)
        Vinny.setTabOrder(self.InventoryAddCopy, self.InventoryEditBottle)
        Vinny.setTabOrder(self.InventoryEditBottle, self.InventoryMoveBottle)
        Vinny.setTabOrder(self.InventoryMoveBottle, self.InventorySortBy)
        Vinny.setTabOrder(self.InventorySortBy, self.InventorySortAsc)
        Vinny.setTabOrder(self.InventorySortAsc, self.InventorySortDesc)
        Vinny.setTabOrder(self.InventorySortDesc, self.InventoryRefresh)
        Vinny.setTabOrder(self.InventoryRefresh, self.main_tab)
        Vinny.setTabOrder(self.main_tab, self.AddBottleWinery)
        Vinny.setTabOrder(self.AddBottleWinery, self.AddBottleAVA)
        Vinny.setTabOrder(self.AddBottleAVA, self.AddBottleBlendName)
        Vinny.setTabOrder(self.AddBottleBlendName, self.AddBottleVarietal)
        Vinny.setTabOrder(self.AddBottleVarietal, self.AddBottleVintage)
        Vinny.setTabOrder(self.AddBottleVintage, self.AddBottleUPC)
        Vinny.setTabOrder(self.AddBottleUPC, self.AddBottleBottleSize)
        Vinny.setTabOrder(self.AddBottleBottleSize, self.AddBottleType)
        Vinny.setTabOrder(self.AddBottleType, self.AddBottleMSRP)
        Vinny.setTabOrder(self.AddBottleMSRP, self.AddBottleCurrentValue)
        Vinny.setTabOrder(self.AddBottleCurrentValue, self.AddBottleComments)
        Vinny.setTabOrder(self.AddBottleComments, self.AddBottleCellarOnly)
        Vinny.setTabOrder(self.AddBottleCellarOnly, self.AddBottleSearch)
        Vinny.setTabOrder(self.AddBottleSearch, self.AddBottleUpdate)
        Vinny.setTabOrder(self.AddBottleUpdate, self.AddBottleMove)
        Vinny.setTabOrder(self.AddBottleMove, self.AddBottleSelLocation)
        Vinny.setTabOrder(self.AddBottleSelLocation, self.AddBottleLocation)
        Vinny.setTabOrder(self.AddBottleLocation, self.AddBottleSelQty)
        Vinny.setTabOrder(self.AddBottleSelQty, self.AddBottleQty)
        Vinny.setTabOrder(self.AddBottleQty, self.AddBottleAdd)
        Vinny.setTabOrder(self.AddBottleAdd, self.AddBottleGenerateBarcode)
        Vinny.setTabOrder(self.AddBottleGenerateBarcode, self.AddBottleTable)
        Vinny.setTabOrder(self.AddBottleTable, self.HistoryTable)
=======
        self.sort_by.setCurrentIndex(0)
        self.bottle_size.setCurrentIndex(2)
        QtCore.QObject.connect(self.wine_id, QtCore.SIGNAL("returnPressed()"), self.quick_search.animateClick)
        QtCore.QObject.connect(self.location_field, QtCore.SIGNAL("returnPressed()"), self.quick_search.animateClick)
        QtCore.QObject.connect(self.refresh, QtCore.SIGNAL("clicked()"), self.quick_search.click)
        QtCore.QObject.connect(self.cellar_only, QtCore.SIGNAL("toggled(bool)"), self.search.animateClick)
        QtCore.QMetaObject.connectSlotsByName(Vinny)
        Vinny.setTabOrder(self.wine_id, self.location_field)
        Vinny.setTabOrder(self.location_field, self.quick_search)
        Vinny.setTabOrder(self.quick_search, self.invTable)
        Vinny.setTabOrder(self.invTable, self.check_out)
        Vinny.setTabOrder(self.check_out, self.add_copy)
        Vinny.setTabOrder(self.add_copy, self.edit_bottle)
        Vinny.setTabOrder(self.edit_bottle, self.move_bottle)
        Vinny.setTabOrder(self.move_bottle, self.sort_by)
        Vinny.setTabOrder(self.sort_by, self.sort_asc)
        Vinny.setTabOrder(self.sort_asc, self.sort_desc)
        Vinny.setTabOrder(self.sort_desc, self.refresh)
        Vinny.setTabOrder(self.refresh, self.main_tab)
        Vinny.setTabOrder(self.main_tab, self.winery)
        Vinny.setTabOrder(self.winery, self.lineEdit_5)
        Vinny.setTabOrder(self.lineEdit_5, self.blend_name)
        Vinny.setTabOrder(self.blend_name, self.varietal)
        Vinny.setTabOrder(self.varietal, self.vintage)
        Vinny.setTabOrder(self.vintage, self.upc)
        Vinny.setTabOrder(self.upc, self.bottle_size)
        Vinny.setTabOrder(self.bottle_size, self.comboBox)
        Vinny.setTabOrder(self.comboBox, self.msrp)
        Vinny.setTabOrder(self.msrp, self.value)
        Vinny.setTabOrder(self.value, self.comments)
        Vinny.setTabOrder(self.comments, self.cellar_only)
        Vinny.setTabOrder(self.cellar_only, self.search)
        Vinny.setTabOrder(self.search, self.update)
        Vinny.setTabOrder(self.update, self.move_bottle_2)
        Vinny.setTabOrder(self.move_bottle_2, self.sel_location)
        Vinny.setTabOrder(self.sel_location, self.location)
        Vinny.setTabOrder(self.location, self.sel_quantity)
        Vinny.setTabOrder(self.sel_quantity, self.qty)
        Vinny.setTabOrder(self.qty, self.add)
        Vinny.setTabOrder(self.add, self.generate_barcode)
        Vinny.setTabOrder(self.generate_barcode, self.search_result_table)
        Vinny.setTabOrder(self.search_result_table, self.history_table)
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d

    def retranslateUi(self, Vinny):
        Vinny.setWindowTitle(QtWidgets.QApplication.translate("Vinny", "Vinny ", None, -1))
        self.bottle_lookup.setTitle(QtWidgets.QApplication.translate("Vinny", "Bottle Lookup", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Vinny", "Enter", None, -1))
<<<<<<< HEAD
        self.InventoryWineID.setPlaceholderText(QtWidgets.QApplication.translate("Vinny", "Wine ID", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Vinny", "Or", None, -1))
        self.InventoryLocation.setPlaceholderText(QtWidgets.QApplication.translate("Vinny", "Location", None, -1))
        self.InventorySearch.setText(QtWidgets.QApplication.translate("Vinny", "Search", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Vinny", "Sort By:", None, -1))
        self.InventorySortBy.setCurrentText(QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.InventorySortBy.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.InventorySortBy.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Varietal", None, -1))
        self.InventorySortBy.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Vintage", None, -1))
        self.InventorySortBy.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Blend Name", None, -1))
        self.InventorySortBy.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Type", None, -1))
        self.InventorySortBy.setItemText(5, QtWidgets.QApplication.translate("Vinny", "MSRP", None, -1))
        self.InventorySortBy.setItemText(6, QtWidgets.QApplication.translate("Vinny", "Value", None, -1))
        self.InventorySortBy.setItemText(7, QtWidgets.QApplication.translate("Vinny", "AVA", None, -1))
        self.InventorySortAsc.setText(QtWidgets.QApplication.translate("Vinny", "Ascending", None, -1))
        self.InventorySortDesc.setText(QtWidgets.QApplication.translate("Vinny", "Descending", None, -1))
        self.InventoryRefresh.setText(QtWidgets.QApplication.translate("Vinny", "Refresh Inventory", None, -1))
        self.InventoryCheckOut.setText(QtWidgets.QApplication.translate("Vinny", "Check Out", None, -1))
        self.InventoryAddCopy.setText(QtWidgets.QApplication.translate("Vinny", "Add Copy", None, -1))
        self.InventoryEditBottle.setText(QtWidgets.QApplication.translate("Vinny", "Edit Bottle", None, -1))
        self.InventoryMoveBottle.setText(QtWidgets.QApplication.translate("Vinny", "Move Bottle", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.inventory), QtWidgets.QApplication.translate("Vinny", "Inventory", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Vinny", "Matches", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("Vinny", "Actions", None, -1))
        self.AddBottleSelLocation.setText(QtWidgets.QApplication.translate("Vinny", "Location", None, -1))
        self.AddBottleSelQty.setText(QtWidgets.QApplication.translate("Vinny", "Quantity", None, -1))
        self.AddBottleAdd.setText(QtWidgets.QApplication.translate("Vinny", "Add to Cellar", None, -1))
        self.AddBottleGenerateBarcode.setText(QtWidgets.QApplication.translate("Vinny", "Generate Barcode", None, -1))
=======
        self.wine_id.setPlaceholderText(QtWidgets.QApplication.translate("Vinny", "Wine ID", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Vinny", "Or", None, -1))
        self.location_field.setPlaceholderText(QtWidgets.QApplication.translate("Vinny", "Location", None, -1))
        self.quick_search.setText(QtWidgets.QApplication.translate("Vinny", "Search", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Vinny", "Sort By:", None, -1))
        self.sort_by.setCurrentText(QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.sort_by.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.sort_by.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Varietal", None, -1))
        self.sort_by.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Vintage", None, -1))
        self.sort_by.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Blend Name", None, -1))
        self.sort_by.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Type", None, -1))
        self.sort_by.setItemText(5, QtWidgets.QApplication.translate("Vinny", "MSRP", None, -1))
        self.sort_by.setItemText(6, QtWidgets.QApplication.translate("Vinny", "Value", None, -1))
        self.sort_by.setItemText(7, QtWidgets.QApplication.translate("Vinny", "AVA", None, -1))
        self.sort_asc.setText(QtWidgets.QApplication.translate("Vinny", "Ascending", None, -1))
        self.sort_desc.setText(QtWidgets.QApplication.translate("Vinny", "Descending", None, -1))
        self.refresh.setText(QtWidgets.QApplication.translate("Vinny", "Refresh Inventory", None, -1))
        self.check_out.setText(QtWidgets.QApplication.translate("Vinny", "Check Out", None, -1))
        self.add_copy.setText(QtWidgets.QApplication.translate("Vinny", "Add Copy", None, -1))
        self.edit_bottle.setText(QtWidgets.QApplication.translate("Vinny", "Edit Bottle", None, -1))
        self.move_bottle.setText(QtWidgets.QApplication.translate("Vinny", "Move Bottle", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.inventory), QtWidgets.QApplication.translate("Vinny", "Inventory", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Vinny", "Matches", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("Vinny", "Actions", None, -1))
        self.sel_location.setText(QtWidgets.QApplication.translate("Vinny", "Location", None, -1))
        self.sel_quantity.setText(QtWidgets.QApplication.translate("Vinny", "Quantity", None, -1))
        self.add.setText(QtWidgets.QApplication.translate("Vinny", "Add to Cellar", None, -1))
        self.generate_barcode.setText(QtWidgets.QApplication.translate("Vinny", "Generate Barcode", None, -1))
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Vinny", "Wine Information", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Vinny", "American Viticulture Area", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Vinny", "Varietal", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Vinny", "UPC Code", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Vinny", "Type", None, -1))
<<<<<<< HEAD
        self.AddBottleType.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Table", None, -1))
        self.AddBottleType.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Dessert", None, -1))
        self.AddBottleType.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Sparkling", None, -1))
=======
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Table", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Dessert", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Sparkling", None, -1))
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.label_10.setText(QtWidgets.QApplication.translate("Vinny", "Current Value", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Vinny", "Blend Name", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Vinny", "Vintage", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Vinny", "Bottle Size", None, -1))
<<<<<<< HEAD
        self.AddBottleBottleSize.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Split (187.5 mL)", None, -1))
        self.AddBottleBottleSize.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Half (375 mL)", None, -1))
        self.AddBottleBottleSize.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Standard (750 mL)", None, -1))
        self.AddBottleBottleSize.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Magnum (1.5 L)", None, -1))
        self.AddBottleBottleSize.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Double Magnum (3.0 L)", None, -1))
        self.AddBottleBottleSize.setItemText(5, QtWidgets.QApplication.translate("Vinny", "Jeroboam (4.5 L)", None, -1))
        self.AddBottleBottleSize.setItemText(6, QtWidgets.QApplication.translate("Vinny", "Imperial (6.0 L)", None, -1))
        self.AddBottleBottleSize.setItemText(7, QtWidgets.QApplication.translate("Vinny", "Salmanazar (9.0 L)", None, -1))
        self.AddBottleBottleSize.setItemText(8, QtWidgets.QApplication.translate("Vinny", "Other...", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Vinny", "MSRP", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Vinny", "Comments", None, -1))
        self.AddBottleCellarOnly.setText(QtWidgets.QApplication.translate("Vinny", "Limit Search to My Cellar", None, -1))
        self.AddBottleSearch.setText(QtWidgets.QApplication.translate("Vinny", "Search", None, -1))
        self.AddBottleCheckOut.setText(QtWidgets.QApplication.translate("Vinny", "Check Out", None, -1))
        self.AddBottleUpdate.setText(QtWidgets.QApplication.translate("Vinny", "Update Bottle", None, -1))
        self.AddBottleMove.setText(QtWidgets.QApplication.translate("Vinny", "Move Bottle", None, -1))
=======
        self.bottle_size.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Split (187.5 mL)", None, -1))
        self.bottle_size.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Half (375 mL)", None, -1))
        self.bottle_size.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Standard (750 mL)", None, -1))
        self.bottle_size.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Magnum (1.5 L)", None, -1))
        self.bottle_size.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Double Magnum (3.0 L)", None, -1))
        self.bottle_size.setItemText(5, QtWidgets.QApplication.translate("Vinny", "Jeroboam (4.5 L)", None, -1))
        self.bottle_size.setItemText(6, QtWidgets.QApplication.translate("Vinny", "Imperial (6.0 L)", None, -1))
        self.bottle_size.setItemText(7, QtWidgets.QApplication.translate("Vinny", "Salmanazar (9.0 L)", None, -1))
        self.bottle_size.setItemText(8, QtWidgets.QApplication.translate("Vinny", "Other...", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Vinny", "MSRP", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Vinny", "Comments", None, -1))
        self.cellar_only.setText(QtWidgets.QApplication.translate("Vinny", "Limit Search to My Cellar", None, -1))
        self.search.setText(QtWidgets.QApplication.translate("Vinny", "Search", None, -1))
        self.update.setText(QtWidgets.QApplication.translate("Vinny", "Update Bottle", None, -1))
        self.move_bottle_2.setText(QtWidgets.QApplication.translate("Vinny", "Move Bottle", None, -1))
>>>>>>> b3d6173d6eddc5ed308fdb94fd8375d9fd727f3d
        self.main_tab.setTabText(self.main_tab.indexOf(self.find), QtWidgets.QApplication.translate("Vinny", "Add Bottle", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.history), QtWidgets.QApplication.translate("Vinny", "History", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("Vinny", "File", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("Vinny", "Edit", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("Vinny", "Settings", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("Vinny", "Import...", None, -1))
        self.actionExport.setText(QtWidgets.QApplication.translate("Vinny", "Export...", None, -1))

import icons_rc
