# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\GitHub\Wine-Inventory\interface.ui',
# licensing of 'D:\Documents\GitHub\Wine-Inventory\interface.ui' applies.
#
# Created: Fri Mar 29 15:00:29 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Vinny(object):
    def setupUi(self, Vinny):
        Vinny.setObjectName("Vinny")
        Vinny.resize(1198, 890)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Wine/wine/icons8-bar-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Vinny.setWindowIcon(icon)
        Vinny.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(Vinny)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.main_tab.setObjectName("main_tab")
        self.inventory = QtWidgets.QWidget()
        self.inventory.setObjectName("inventory")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inventory)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bottle_lookup = QtWidgets.QGroupBox(self.inventory)
        self.bottle_lookup.setObjectName("bottle_lookup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bottle_lookup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.bottle_lookup)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.InventoryWineID = QtWidgets.QLineEdit(self.bottle_lookup)
        self.InventoryWineID.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.InventoryWineID.setText("")
        self.InventoryWineID.setClearButtonEnabled(False)
        self.InventoryWineID.setObjectName("InventoryWineID")
        self.verticalLayout.addWidget(self.InventoryWineID)
        self.label = QtWidgets.QLabel(self.bottle_lookup)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.InventoryLocation = QtWidgets.QLineEdit(self.bottle_lookup)
        self.InventoryLocation.setObjectName("InventoryLocation")
        self.verticalLayout.addWidget(self.InventoryLocation)
        self.InventorySearch = QtWidgets.QPushButton(self.bottle_lookup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Actions/actions/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InventorySearch.setIcon(icon1)
        self.InventorySearch.setCheckable(False)
        self.InventorySearch.setObjectName("InventorySearch")
        self.verticalLayout.addWidget(self.InventorySearch)
        self.horizontalLayout.addWidget(self.bottle_lookup)
        self.groupBox = QtWidgets.QGroupBox(self.inventory)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InventorySortBy = QtWidgets.QComboBox(self.groupBox)
        self.InventorySortBy.setObjectName("InventorySortBy")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.InventorySortBy.addItem("")
        self.verticalLayout_3.addWidget(self.InventorySortBy)
        self.InventorySortAsc = QtWidgets.QRadioButton(self.groupBox)
        self.InventorySortAsc.setChecked(True)
        self.InventorySortAsc.setObjectName("InventorySortAsc")
        self.verticalLayout_3.addWidget(self.InventorySortAsc)
        self.InventorySortDesc = QtWidgets.QRadioButton(self.groupBox)
        self.InventorySortDesc.setObjectName("InventorySortDesc")
        self.verticalLayout_3.addWidget(self.InventorySortDesc)
        self.InventoryRefresh = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Actions/actions/stock_refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InventoryRefresh.setIcon(icon2)
        self.InventoryRefresh.setObjectName("InventoryRefresh")
        self.verticalLayout_3.addWidget(self.InventoryRefresh)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.InventoryTable = QtWidgets.QTableWidget(self.inventory)
        self.InventoryTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.InventoryTable.setObjectName("InventoryTable")
        self.InventoryTable.setColumnCount(0)
        self.InventoryTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.InventoryTable)
        self.InventoryCheckOut = QtWidgets.QPushButton(self.inventory)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Wine/wine/icons8-wine-bottle-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InventoryCheckOut.setIcon(icon3)
        self.InventoryCheckOut.setObjectName("InventoryCheckOut")
        self.verticalLayout_2.addWidget(self.InventoryCheckOut)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.InventoryAddCopy = QtWidgets.QPushButton(self.inventory)
        self.InventoryAddCopy.setObjectName("InventoryAddCopy")
        self.horizontalLayout_6.addWidget(self.InventoryAddCopy)
        self.InventoryEditBottle = QtWidgets.QPushButton(self.inventory)
        self.InventoryEditBottle.setObjectName("InventoryEditBottle")
        self.horizontalLayout_6.addWidget(self.InventoryEditBottle)
        self.InventoryMoveBottle = QtWidgets.QPushButton(self.inventory)
        self.InventoryMoveBottle.setObjectName("InventoryMoveBottle")
        self.horizontalLayout_6.addWidget(self.InventoryMoveBottle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.main_tab.addTab(self.inventory, "")
        self.wines = QtWidgets.QWidget()
        self.wines.setObjectName("wines")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.wines)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.wines)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.AddBottleSelLocation = QtWidgets.QRadioButton(self.groupBox_5)
        self.AddBottleSelLocation.setChecked(True)
        self.AddBottleSelLocation.setObjectName("AddBottleSelLocation")
        self.verticalLayout_9.addWidget(self.AddBottleSelLocation)
        self.AddBottleLocation = QtWidgets.QLineEdit(self.groupBox_5)
        self.AddBottleLocation.setObjectName("AddBottleLocation")
        self.verticalLayout_9.addWidget(self.AddBottleLocation)
        self.AddBottleSelQty = QtWidgets.QRadioButton(self.groupBox_5)
        self.AddBottleSelQty.setObjectName("AddBottleSelQty")
        self.verticalLayout_9.addWidget(self.AddBottleSelQty)
        self.AddBottleQty = QtWidgets.QLineEdit(self.groupBox_5)
        self.AddBottleQty.setObjectName("AddBottleQty")
        self.verticalLayout_9.addWidget(self.AddBottleQty)
        self.AddBottleAdd = QtWidgets.QPushButton(self.groupBox_5)
        self.AddBottleAdd.setObjectName("AddBottleAdd")
        self.verticalLayout_9.addWidget(self.AddBottleAdd)
        self.AddBottleGenerateBarcode = QtWidgets.QPushButton(self.groupBox_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Actions/actions/icons8-barcode-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddBottleGenerateBarcode.setIcon(icon4)
        self.AddBottleGenerateBarcode.setObjectName("AddBottleGenerateBarcode")
        self.verticalLayout_9.addWidget(self.AddBottleGenerateBarcode)
        self.gridLayout_3.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.wines)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.AddBottleTable = QtWidgets.QTableWidget(self.wines)
        self.AddBottleTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.AddBottleTable.setObjectName("AddBottleTable")
        self.AddBottleTable.setColumnCount(0)
        self.AddBottleTable.setRowCount(0)
        self.verticalLayout_6.addWidget(self.AddBottleTable)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 1, 4, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.wines)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.AddBottleComments = QtWidgets.QTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddBottleComments.sizePolicy().hasHeightForWidth())
        self.AddBottleComments.setSizePolicy(sizePolicy)
        self.AddBottleComments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.AddBottleComments.setPlaceholderText("")
        self.AddBottleComments.setObjectName("AddBottleComments")
        self.gridLayout_2.addWidget(self.AddBottleComments, 4, 0, 2, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.AddBottleRating = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddBottleRating.sizePolicy().hasHeightForWidth())
        self.AddBottleRating.setSizePolicy(sizePolicy)
        self.AddBottleRating.setObjectName("AddBottleRating")
        self.gridLayout_2.addWidget(self.AddBottleRating, 4, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.AddBottleAVA = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleAVA.setPlaceholderText("")
        self.AddBottleAVA.setObjectName("AddBottleAVA")
        self.verticalLayout_5.addWidget(self.AddBottleAVA)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.AddBottleVarietal = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleVarietal.setPlaceholderText("")
        self.AddBottleVarietal.setObjectName("AddBottleVarietal")
        self.verticalLayout_5.addWidget(self.AddBottleVarietal)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.AddBottleUPC = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleUPC.setObjectName("AddBottleUPC")
        self.verticalLayout_5.addWidget(self.AddBottleUPC)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.AddBottleType = QtWidgets.QComboBox(self.groupBox_3)
        self.AddBottleType.setObjectName("AddBottleType")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.AddBottleType.addItem("")
        self.verticalLayout_5.addWidget(self.AddBottleType)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.AddBottleCurrentValue = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleCurrentValue.setObjectName("AddBottleCurrentValue")
        self.verticalLayout_5.addWidget(self.AddBottleCurrentValue)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.AddBottleWinery = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleWinery.setPlaceholderText("")
        self.AddBottleWinery.setObjectName("AddBottleWinery")
        self.verticalLayout_4.addWidget(self.AddBottleWinery)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.AddBottleBlendName = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleBlendName.setObjectName("AddBottleBlendName")
        self.verticalLayout_4.addWidget(self.AddBottleBlendName)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.AddBottleVintage = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleVintage.setObjectName("AddBottleVintage")
        self.verticalLayout_4.addWidget(self.AddBottleVintage)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.AddBottleBottleSize = QtWidgets.QComboBox(self.groupBox_3)
        self.AddBottleBottleSize.setObjectName("AddBottleBottleSize")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.AddBottleBottleSize.addItem("")
        self.verticalLayout_4.addWidget(self.AddBottleBottleSize)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.AddBottleMSRP = QtWidgets.QLineEdit(self.groupBox_3)
        self.AddBottleMSRP.setObjectName("AddBottleMSRP")
        self.verticalLayout_4.addWidget(self.AddBottleMSRP)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.AddBottleSearch = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddBottleSearch.sizePolicy().hasHeightForWidth())
        self.AddBottleSearch.setSizePolicy(sizePolicy)
        self.AddBottleSearch.setIcon(icon1)
        self.AddBottleSearch.setObjectName("AddBottleSearch")
        self.verticalLayout_7.addWidget(self.AddBottleSearch)
        self.AddBottleUpdate = QtWidgets.QPushButton(self.groupBox_3)
        self.AddBottleUpdate.setObjectName("AddBottleUpdate")
        self.verticalLayout_7.addWidget(self.AddBottleUpdate)
        self.AddBottleClearFields = QtWidgets.QPushButton(self.groupBox_3)
        self.AddBottleClearFields.setObjectName("AddBottleClearFields")
        self.verticalLayout_7.addWidget(self.AddBottleClearFields)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.main_tab.addTab(self.wines, "")
        self.history = QtWidgets.QWidget()
        self.history.setObjectName("history")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.history)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.HistoryTable = QtWidgets.QTableWidget(self.history)
        self.HistoryTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.HistoryTable.setObjectName("HistoryTable")
        self.HistoryTable.setColumnCount(0)
        self.HistoryTable.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.HistoryTable)
        self.main_tab.addTab(self.history, "")
        self.horizontalLayout_2.addWidget(self.main_tab)
        Vinny.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Vinny)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDelete = QtWidgets.QMenu(self.menuEdit)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Places/places/gnome-stock-trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuDelete.setIcon(icon5)
        self.menuDelete.setObjectName("menuDelete")
        Vinny.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Vinny)
        self.statusbar.setObjectName("statusbar")
        Vinny.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(Vinny)
        self.actionSettings.setShortcutContext(QtCore.Qt.WidgetWithChildrenShortcut)
        self.actionSettings.setObjectName("actionSettings")
        self.actionImport = QtWidgets.QAction(Vinny)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Actions/actions/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon6)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(Vinny)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Mimetypes/mimetypes/x-office-spreadsheet.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon7)
        self.actionExport.setObjectName("actionExport")
        self.actionPreferences = QtWidgets.QAction(Vinny)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Catagories/categories/applications-system.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon8)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionDelete_Wine = QtWidgets.QAction(Vinny)
        self.actionDelete_Wine.setObjectName("actionDelete_Wine")
        self.actionWine = QtWidgets.QAction(Vinny)
        self.actionWine.setObjectName("actionWine")
        self.actionBottle = QtWidgets.QAction(Vinny)
        self.actionBottle.setObjectName("actionBottle")
        self.actionGenerate_Barcode = QtWidgets.QAction(Vinny)
        self.actionGenerate_Barcode.setIcon(icon4)
        self.actionGenerate_Barcode.setObjectName("actionGenerate_Barcode")
        self.actionBackup_Database = QtWidgets.QAction(Vinny)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Places/places/gnome-mime-x-directory-smb-workgroup.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackup_Database.setIcon(icon9)
        self.actionBackup_Database.setObjectName("actionBackup_Database")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBackup_Database)
        self.menuDelete.addAction(self.actionBottle)
        self.menuDelete.addAction(self.actionWine)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionGenerate_Barcode)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuDelete.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Vinny)
        self.main_tab.setCurrentIndex(0)
        self.InventorySortBy.setCurrentIndex(0)
        self.AddBottleBottleSize.setCurrentIndex(2)
        QtCore.QObject.connect(self.InventoryWineID, QtCore.SIGNAL("returnPressed()"), self.InventorySearch.animateClick)
        QtCore.QObject.connect(self.InventoryLocation, QtCore.SIGNAL("returnPressed()"), self.InventorySearch.animateClick)
        QtCore.QObject.connect(self.InventoryRefresh, QtCore.SIGNAL("clicked()"), self.InventorySearch.click)
        QtCore.QObject.connect(self.AddBottleWinery, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleBlendName, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleVintage, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleMSRP, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleAVA, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleVarietal, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleUPC, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleType, QtCore.SIGNAL("currentIndexChanged(int)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleCurrentValue, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QObject.connect(self.AddBottleRating, QtCore.SIGNAL("textChanged(QString)"), self.AddBottleSearch.click)
        QtCore.QMetaObject.connectSlotsByName(Vinny)
        Vinny.setTabOrder(self.InventoryWineID, self.InventoryLocation)
        Vinny.setTabOrder(self.InventoryLocation, self.InventorySearch)
        Vinny.setTabOrder(self.InventorySearch, self.InventoryTable)
        Vinny.setTabOrder(self.InventoryTable, self.InventoryCheckOut)
        Vinny.setTabOrder(self.InventoryCheckOut, self.InventoryAddCopy)
        Vinny.setTabOrder(self.InventoryAddCopy, self.InventoryEditBottle)
        Vinny.setTabOrder(self.InventoryEditBottle, self.InventoryMoveBottle)
        Vinny.setTabOrder(self.InventoryMoveBottle, self.InventorySortBy)
        Vinny.setTabOrder(self.InventorySortBy, self.InventorySortAsc)
        Vinny.setTabOrder(self.InventorySortAsc, self.InventorySortDesc)
        Vinny.setTabOrder(self.InventorySortDesc, self.InventoryRefresh)
        Vinny.setTabOrder(self.InventoryRefresh, self.AddBottleWinery)
        Vinny.setTabOrder(self.AddBottleWinery, self.AddBottleAVA)
        Vinny.setTabOrder(self.AddBottleAVA, self.AddBottleBlendName)
        Vinny.setTabOrder(self.AddBottleBlendName, self.AddBottleVarietal)
        Vinny.setTabOrder(self.AddBottleVarietal, self.AddBottleVintage)
        Vinny.setTabOrder(self.AddBottleVintage, self.AddBottleUPC)
        Vinny.setTabOrder(self.AddBottleUPC, self.AddBottleBottleSize)
        Vinny.setTabOrder(self.AddBottleBottleSize, self.AddBottleType)
        Vinny.setTabOrder(self.AddBottleType, self.AddBottleMSRP)
        Vinny.setTabOrder(self.AddBottleMSRP, self.AddBottleCurrentValue)
        Vinny.setTabOrder(self.AddBottleCurrentValue, self.AddBottleSearch)
        Vinny.setTabOrder(self.AddBottleSearch, self.AddBottleUpdate)
        Vinny.setTabOrder(self.AddBottleUpdate, self.AddBottleClearFields)
        Vinny.setTabOrder(self.AddBottleClearFields, self.AddBottleSelLocation)
        Vinny.setTabOrder(self.AddBottleSelLocation, self.AddBottleLocation)
        Vinny.setTabOrder(self.AddBottleLocation, self.AddBottleSelQty)
        Vinny.setTabOrder(self.AddBottleSelQty, self.AddBottleQty)
        Vinny.setTabOrder(self.AddBottleQty, self.AddBottleAdd)
        Vinny.setTabOrder(self.AddBottleAdd, self.AddBottleGenerateBarcode)
        Vinny.setTabOrder(self.AddBottleGenerateBarcode, self.AddBottleTable)
        Vinny.setTabOrder(self.AddBottleTable, self.HistoryTable)

    def retranslateUi(self, Vinny):
        Vinny.setWindowTitle(QtWidgets.QApplication.translate("Vinny", "Vinny ", None, -1))
        self.bottle_lookup.setTitle(QtWidgets.QApplication.translate("Vinny", "Bottle Lookup", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Vinny", "Enter", None, -1))
        self.InventoryWineID.setPlaceholderText(QtWidgets.QApplication.translate("Vinny", "Wine ID", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Vinny", "Or", None, -1))
        self.InventoryLocation.setPlaceholderText(QtWidgets.QApplication.translate("Vinny", "Location", None, -1))
        self.InventorySearch.setText(QtWidgets.QApplication.translate("Vinny", "Search", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Vinny", "Sort By:", None, -1))
        self.InventorySortBy.setCurrentText(QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.InventorySortBy.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.InventorySortBy.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Region", None, -1))
        self.InventorySortBy.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Blend Name", None, -1))
        self.InventorySortBy.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Varietal", None, -1))
        self.InventorySortBy.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Vintage", None, -1))
        self.InventorySortBy.setItemText(5, QtWidgets.QApplication.translate("Vinny", "Type", None, -1))
        self.InventorySortBy.setItemText(6, QtWidgets.QApplication.translate("Vinny", "MSRP", None, -1))
        self.InventorySortBy.setItemText(7, QtWidgets.QApplication.translate("Vinny", "Value", None, -1))
        self.InventorySortBy.setItemText(8, QtWidgets.QApplication.translate("Vinny", "Rating", None, -1))
        self.InventorySortBy.setItemText(9, QtWidgets.QApplication.translate("Vinny", "Date In", None, -1))
        self.InventorySortAsc.setText(QtWidgets.QApplication.translate("Vinny", "Ascending", None, -1))
        self.InventorySortDesc.setText(QtWidgets.QApplication.translate("Vinny", "Descending", None, -1))
        self.InventoryRefresh.setText(QtWidgets.QApplication.translate("Vinny", "Refresh Inventory", None, -1))
        self.InventoryCheckOut.setText(QtWidgets.QApplication.translate("Vinny", "Check Out", None, -1))
        self.InventoryAddCopy.setText(QtWidgets.QApplication.translate("Vinny", "Add Copy", None, -1))
        self.InventoryEditBottle.setText(QtWidgets.QApplication.translate("Vinny", "Edit Wine", None, -1))
        self.InventoryMoveBottle.setText(QtWidgets.QApplication.translate("Vinny", "Move Bottle", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.inventory), QtWidgets.QApplication.translate("Vinny", "Bottles", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("Vinny", "Actions", None, -1))
        self.AddBottleSelLocation.setText(QtWidgets.QApplication.translate("Vinny", "Location", None, -1))
        self.AddBottleSelQty.setText(QtWidgets.QApplication.translate("Vinny", "Quantity", None, -1))
        self.AddBottleAdd.setText(QtWidgets.QApplication.translate("Vinny", "Add to Cellar", None, -1))
        self.AddBottleGenerateBarcode.setText(QtWidgets.QApplication.translate("Vinny", "Generate Barcode", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Vinny", "Matches", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Vinny", "Wine Information", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Vinny", "Rating", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Vinny", "Comments", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Vinny", "Region", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Vinny", "Varietal", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Vinny", "UPC Code", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Vinny", "Type", None, -1))
        self.AddBottleType.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Red", None, -1))
        self.AddBottleType.setItemText(1, QtWidgets.QApplication.translate("Vinny", "White", None, -1))
        self.AddBottleType.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Rose", None, -1))
        self.AddBottleType.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Dessert", None, -1))
        self.AddBottleType.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Sparkling", None, -1))
        self.AddBottleType.setItemText(5, QtWidgets.QApplication.translate("Vinny", "Other...", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Vinny", "Current Value", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Vinny", "Winery", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Vinny", "Blend Name", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Vinny", "Vintage", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Vinny", "Bottle Size", None, -1))
        self.AddBottleBottleSize.setItemText(0, QtWidgets.QApplication.translate("Vinny", "Split (187.5 mL)", None, -1))
        self.AddBottleBottleSize.setItemText(1, QtWidgets.QApplication.translate("Vinny", "Half (375 mL)", None, -1))
        self.AddBottleBottleSize.setItemText(2, QtWidgets.QApplication.translate("Vinny", "Standard (750 mL)", None, -1))
        self.AddBottleBottleSize.setItemText(3, QtWidgets.QApplication.translate("Vinny", "Magnum (1.5 L)", None, -1))
        self.AddBottleBottleSize.setItemText(4, QtWidgets.QApplication.translate("Vinny", "Double Magnum (3.0 L)", None, -1))
        self.AddBottleBottleSize.setItemText(5, QtWidgets.QApplication.translate("Vinny", "Jeroboam (4.5 L)", None, -1))
        self.AddBottleBottleSize.setItemText(6, QtWidgets.QApplication.translate("Vinny", "Imperial (6.0 L)", None, -1))
        self.AddBottleBottleSize.setItemText(7, QtWidgets.QApplication.translate("Vinny", "Salmanazar (9.0 L)", None, -1))
        self.AddBottleBottleSize.setItemText(8, QtWidgets.QApplication.translate("Vinny", "Other...", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Vinny", "MSRP", None, -1))
        self.AddBottleSearch.setText(QtWidgets.QApplication.translate("Vinny", "Search", None, -1))
        self.AddBottleUpdate.setText(QtWidgets.QApplication.translate("Vinny", "Update Wine", None, -1))
        self.AddBottleClearFields.setText(QtWidgets.QApplication.translate("Vinny", "Clear Fields", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.wines), QtWidgets.QApplication.translate("Vinny", "Wines", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.history), QtWidgets.QApplication.translate("Vinny", "History", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("Vinny", "File", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("Vinny", "Edit", None, -1))
        self.menuDelete.setTitle(QtWidgets.QApplication.translate("Vinny", "Delete...", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("Vinny", "Settings", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("Vinny", "Import...", None, -1))
        self.actionExport.setText(QtWidgets.QApplication.translate("Vinny", "Export...", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("Vinny", "Preferences", None, -1))
        self.actionDelete_Wine.setText(QtWidgets.QApplication.translate("Vinny", "Delete Wine", None, -1))
        self.actionWine.setText(QtWidgets.QApplication.translate("Vinny", "Wine", None, -1))
        self.actionBottle.setText(QtWidgets.QApplication.translate("Vinny", "Bottle", None, -1))
        self.actionGenerate_Barcode.setText(QtWidgets.QApplication.translate("Vinny", "Generate Barcode", None, -1))
        self.actionBackup_Database.setText(QtWidgets.QApplication.translate("Vinny", "Backup Database", None, -1))

import icons_rc
